name: Discord Push Notifier

on: [push]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send message to Discord
        run: |
          curl -H "Content-Type: application/json" \
          -d "{\"content\":\"📢 **${{ github.actor }}** pushed new commits to **${{ github.repository }}** on branch **${{ github.ref_name }}**.\"}" \
          ${{ secrets.DISCORD_WEBHOOK }}
